# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/piotrwyrw/WebServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/piotrwyrw/WebServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/piotrwyrw/WebServer/CMakeFiles /Users/piotrwyrw/WebServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/piotrwyrw/WebServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ketamine

# Build rule for target.
ketamine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ketamine
.PHONY : ketamine

# fast build rule for target.
ketamine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/build
.PHONY : ketamine/fast

src/cfgroute.o: src/cfgroute.c.o
.PHONY : src/cfgroute.o

# target to build an object file
src/cfgroute.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/cfgroute.c.o
.PHONY : src/cfgroute.c.o

src/cfgroute.i: src/cfgroute.c.i
.PHONY : src/cfgroute.i

# target to preprocess a source file
src/cfgroute.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/cfgroute.c.i
.PHONY : src/cfgroute.c.i

src/cfgroute.s: src/cfgroute.c.s
.PHONY : src/cfgroute.s

# target to generate assembly for a file
src/cfgroute.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/cfgroute.c.s
.PHONY : src/cfgroute.c.s

src/client.o: src/client.c.o
.PHONY : src/client.o

# target to build an object file
src/client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/client.c.o
.PHONY : src/client.c.o

src/client.i: src/client.c.i
.PHONY : src/client.i

# target to preprocess a source file
src/client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/client.c.i
.PHONY : src/client.c.i

src/client.s: src/client.c.s
.PHONY : src/client.s

# target to generate assembly for a file
src/client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/client.c.s
.PHONY : src/client.c.s

src/fio.o: src/fio.c.o
.PHONY : src/fio.o

# target to build an object file
src/fio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/fio.c.o
.PHONY : src/fio.c.o

src/fio.i: src/fio.c.i
.PHONY : src/fio.i

# target to preprocess a source file
src/fio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/fio.c.i
.PHONY : src/fio.c.i

src/fio.s: src/fio.c.s
.PHONY : src/fio.s

# target to generate assembly for a file
src/fio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/fio.c.s
.PHONY : src/fio.c.s

src/global.o: src/global.c.o
.PHONY : src/global.o

# target to build an object file
src/global.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/global.c.o
.PHONY : src/global.c.o

src/global.i: src/global.c.i
.PHONY : src/global.i

# target to preprocess a source file
src/global.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/global.c.i
.PHONY : src/global.c.i

src/global.s: src/global.c.s
.PHONY : src/global.s

# target to generate assembly for a file
src/global.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/global.c.s
.PHONY : src/global.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/main.c.s
.PHONY : src/main.c.s

src/parse.o: src/parse.c.o
.PHONY : src/parse.o

# target to build an object file
src/parse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/parse.c.o
.PHONY : src/parse.c.o

src/parse.i: src/parse.c.i
.PHONY : src/parse.i

# target to preprocess a source file
src/parse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/parse.c.i
.PHONY : src/parse.c.i

src/parse.s: src/parse.c.s
.PHONY : src/parse.s

# target to generate assembly for a file
src/parse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/parse.c.s
.PHONY : src/parse.c.s

src/routing.o: src/routing.c.o
.PHONY : src/routing.o

# target to build an object file
src/routing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/routing.c.o
.PHONY : src/routing.c.o

src/routing.i: src/routing.c.i
.PHONY : src/routing.i

# target to preprocess a source file
src/routing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/routing.c.i
.PHONY : src/routing.c.i

src/routing.s: src/routing.c.s
.PHONY : src/routing.s

# target to generate assembly for a file
src/routing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/routing.c.s
.PHONY : src/routing.c.s

src/server.o: src/server.c.o
.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/server.c.s
.PHONY : src/server.c.s

src/threadsafe.o: src/threadsafe.c.o
.PHONY : src/threadsafe.o

# target to build an object file
src/threadsafe.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/threadsafe.c.o
.PHONY : src/threadsafe.c.o

src/threadsafe.i: src/threadsafe.c.i
.PHONY : src/threadsafe.i

# target to preprocess a source file
src/threadsafe.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/threadsafe.c.i
.PHONY : src/threadsafe.c.i

src/threadsafe.s: src/threadsafe.c.s
.PHONY : src/threadsafe.s

# target to generate assembly for a file
src/threadsafe.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ketamine.dir/build.make CMakeFiles/ketamine.dir/src/threadsafe.c.s
.PHONY : src/threadsafe.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ketamine"
	@echo "... src/cfgroute.o"
	@echo "... src/cfgroute.i"
	@echo "... src/cfgroute.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/fio.o"
	@echo "... src/fio.i"
	@echo "... src/fio.s"
	@echo "... src/global.o"
	@echo "... src/global.i"
	@echo "... src/global.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parse.o"
	@echo "... src/parse.i"
	@echo "... src/parse.s"
	@echo "... src/routing.o"
	@echo "... src/routing.i"
	@echo "... src/routing.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/threadsafe.o"
	@echo "... src/threadsafe.i"
	@echo "... src/threadsafe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

